### PR TITLE
CNV-39557: Update one of Feature highlights links in the Overview page

### PR DESCRIPTION
**Pull request by hstastna**
## 📝 Description

**Fixes:**
https://issues.redhat.com/browse/CNV-39557

Replace older _Automatic Windows VirtualMachine installation_ link by the new article _Save memory with OpenShift Virtualization using Free Page Reporting_.

## 🎥 Screenshots
**Before:**
link_before

**After:**
link_after

### CODE REVIEW

**Comment by hstastna** [comment]
@avivtur @metalice @pcbailey @upalatucci @vojtechszocs please review

**Comment by hstastna** [comment]
@avivtur @metalice @pcbailey @upalatucci @vojtechszocs please review

**Review by avivtur — APPROVED** [review]

**Pull request merged**
