### PR TITLE
Move VM Details' Scheduling section to new Scheduling tab

### PR DESCRIPTION
**Pull request by hstastna**
## 📝 Description
Move _Scheduling and resources requirements_ section in the VM _Details_ tab to the new _Scheduling_ tab, make the section as a separate tab, according to the new design updates.

## 🎥 Demo
_Before:_
 _Scheduling and resources requirements_ section present in the VM _Details_ tab:
scheduling_before

_After:_
No any _Scheduling and resources requirements_ section in the VM _Details_ tab:
afterr
A new, separate _Scheduling_ tab:
scheduling_after

### CODE REVIEW

**Comment by yaacov** [comment]
/lgtm

NOTE:
changes needed in the details tab, in a folow up PR
moving the edit functionality from the details tab in folow up PR

**Comment by hstastna** [comment]
@glekner @avivtur @metalice @pcbailey @yzamir @vojtechszocs please review

**Comment by yaacov** [comment]
/hold
require rebase

**Pull request merged**
