### PR TITLE
Bug 2134668: Display correct command with username for SSH

### PR DESCRIPTION
**Pull request by hstastna**
## 📝 Description

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2134668

This is the cherry-pick of: https://github.com/kubevirt-ui/kubevirt-plugin/pull/923 + fixed merge conflicts.

Get the correct cloud-init credentials even when the VM is stopped and generate the ssh command properly (SSH over NodePort).
Disable the SSH over NodePort related checkbox and show the tooltip on hover to inform the user in case that there is no username set.

### CODE REVIEW

**Comment by hstastna** [comment]
@avivtur @metalice @pcbailey @yzamir @vojtechszocs please review

**Review by avivtur — APPROVED** [review]

**Comment by hstastna** [comment]
@avivtur @metalice @pcbailey @yzamir @vojtechszocs please review

**Pull request merged**
