### PR TITLE
Revert "Bug 2097586: fix storage profile settings checkbox"

### PR DESCRIPTION
**Pull request by avivtur**
Reverts kubevirt-ui/kubevirt-plugin#652

reverting as it is not the right solution and causes more bugs

### CODE REVIEW

**Comment by yaacov** [comment]
@avivtur note, this fix is for 4.12, we will need to back-port it to 4.11

**Comment by avivtur** [comment]
closing in favor of https://github.com/kubevirt-ui/kubevirt-plugin/pull/670

**Pull request closed without merging**
