### PR TITLE
Bug 2095953: Moving consoles buttons

### PR DESCRIPTION
**Pull request by metalice**
Signed-off-by: Matan Schatzman <mschatzm@redhat.com>

## 📝 Description

Moving consoles buttons

## 🎥 Demo

After:
image

Before:
image

### CODE REVIEW

**Comment by yaacov** [comment]
@metalice the bug description say:
"""
A. The VNC console dropdown is currently too wide and should be narrower.
B. The Send key dropdown should move to be next to the VNC dropdown, on the right.
C. Send Key should be Send key (lowercase in key)
Version-Release number of selected component (if applicable):
"""

**Comment by yaacov** [comment]
houl

**Comment by metalice** [comment]
> you should not move the "disconnect" button

cool, moved only send keys

**Pull request merged**
