### PR TITLE
Update SDK packages

### PR DESCRIPTION
**Pull request by avivtur**
Signed-off-by: Aviv Turgeman <aturgema@redhat.com>

## 📝 Description

> Update dynamic-plugin-sdk package to 0.0.18 and dynamic-plugin-sdk-webpeck to 0.0.9

### CODE REVIEW

**Comment by upalatucci** [comment]
with the new sdk version, the `useLastNamespace` hook has been fixed. Can we use it in the `useLastNamespacePath` hook? Replacing the temporary logic?

**Comment by avivtur** [comment]
@upalatucci I guess great minds think alike :) 
https://github.com/kubevirt-ui/kubevirt-plugin/pull/965

**Pull request merged**
