### PR TITLE
Bug 2115280: Fix ci HCO version

### PR DESCRIPTION
**Pull request by upalatucci**

### CODE REVIEW

**Review by hstastna — APPROVED** [review]

**Comment by orenc1** [comment]
@upalatucci , since CNV 4.11 (upstream 1.7.0), HCO is deploying the kubevirt console plugin and all of its associated resources.
Thus we're getting the failure on `oc create` of these resources. Not only this, but HCO will reconcile it back.
To test in the CI using a custom image of the console plugin built by the CI, you should change the env var `KV_CONSOLE_PLUGIN_IMAGE` of hco-operator.
Since this is being set by OLM, we need to change it in the CSV so OLM won't reconcile it back.

To do this, you can use this code instead of the existing at: https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/test-prow-e2e.sh#L111-L120

```
echo "Modify the kubevirt console plugin image"
CSV=$(oc get csv -o name -n ${NS})
oc get $CSV -o json > /tmp/hco_csv.json
EXISTING_PLUGIN_IMAGE=$(jq -r '.spec.install.spec.deployments[] | select(.name=="hco-operator").spec.template.spec.containers[0].env[] | select(.name=="KV_CONSOLE_PLUGIN_IMAGE").value' /tmp/hco_csv.json)
sed -i -r "s|$EXISTING_PLUGIN_IMAGE|$KUBEVIRT_PLUGIN_IMAGE|" /tmp/hco_csv.json
oc apply -f /tmp/hco_csv.json

until \
  oc wait pods --for=jsonpath='{.spec.containers[0].image}'="quay.io/kubevirt-ui/kubevirt-plugin:latest" -l app=kubevirt-plugin
  do
    sleep 1
  done
```

**Comment by orenc1** [comment]
sorry, forgot to specify the namespace. 
third line should be:
```
oc get $CSV -n ${NS} -o json > /tmp/hco_csv.json
```

please also add `-n ${NS}` to the `oc wait` command couple of lines below.

(when i tested it, my context was pinned to the correct namespace and i forgot the namespace modifier in this case).

**Comment by orenc1** [comment]
another correction, sorry:
in the `oc wait` command, please put `$KUBEVIRT_PLUGIN_IMAGE` instead of `quay.io/kubevirt-ui/kubevirt-plugin:latest`

**Comment by orenc1** [comment]
also, the wait command in line 128 is not needed, since we're already made the deployment.

**Comment by orenc1** [comment]
in the logs of kubevirt-plugin pod, after replacing it with the image built by the code in the PR, it is suggested that the file `/usr/share/nginx/html/plugin-manifest.json` is missing:
```
2022/09/01 08:35:35 [error] 19#0: *1 open() "/usr/share/nginx/html/plugin-manifest.json" failed (2: No such file or directory), client: 10.130.0.103, server: , request: "GET /plugin-manifest.json HTTP/1.1", host: "kubevirt-plugin-service.kubevirt-hyperconverged.svc.cluster.local:9443", referrer: "https://console-openshift-console.apps.ci-op-gin3jzii-a8c7e.origin-ci-int-aws.dev.rhcloud.com/"
10.130.0.103 - - [01/Sep/2022:08:35:35 +0000] "GET /plugin-manifest.json HTTP/1.1" 404 555 "https://console-openshift-console.apps.ci-op-gin3jzii-a8c7e.origin-ci-int-aws.dev.rhcloud.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/8.5.0 Chrome/91.0.4472.164 Electron/13.2.0 Safari/537.36"
2022/09/01 08:35:35 [info] 19#0: *1 client 10.130.0.103 closed keepalive connection
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt-ui_kubevirt-plugin/854/pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws/1565238855462817792/artifacts/kubevirt-e2e-aws/tests/artifacts/kubevirt-plugin-6559b7648b-sdtrq.logs

**Pull request merged**
