### PR TITLE
Stop disabling static plugin

### PR DESCRIPTION
**Pull request by glekner**
## 📝 Description

https://github.com/openshift/console/pull/11273 is merged.
We can now combine the extensions of the static and dynamic plugin.

### CODE REVIEW

**Comment by glekner** [comment]
/hold

lets wait 1-2 days until console images are updated and contain the needed changes
cc @yaacov

**Comment by yaacov** [comment]
/lgtm

:tada: :cake: :strawberry: :butterfly:

**Comment by glekner** [comment]
image

This is a screenshot from the failing tests
So the e2e environment is not running the latest console code with the `disallowed` flag on the static extensions.
[I think its running 4.10-release](https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml#L12)
We need to figure out how to fix this

cc @yaacov @gouyang

**Comment by yaacov** [comment]
will bumping the version to 4.11 help ?
https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml#L28
https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml#L33

**Pull request merged**
