### PR TITLE
CNV-23926: Fixing warnings and behavior when managing bootable disk and CD-ROM (4.11)

### PR DESCRIPTION
**Pull request by DanaOrr**
## 📝 Description
https://issues.redhat.com/browse/CNV-23926

Fixing 2 problems for 4.11:

1. After we created a new boot source whose type is CD-ROM it doesn't recognize that it is a boot source.

2. After creating the VM we see the pending changes warning for Boot disk, and it's incorrect.

## 🎥 Demo
Before: 
disks4 11Before

After: 
disks4 11After

### CODE REVIEW

**Comment by avivtur** [comment]
This issue is happening only in 4.11? not any version above?

**Comment by DanaOrr** [comment]
@avivtur 
Problem 1 occurs in all versions above 4.11

**Comment by avivtur** [comment]
@DanaOrr Than it should be fixed for all versions, and backport not just for 4.11.
Please Open a new PR for 4.14 and close this one

**Comment by avivtur** [comment]
@pcbailey please review as 4.11 approver

**Pull request merged**
