### PR TITLE
Bug 2086294: [Dark mode] - The number of vms per template in the donuts is visible in overview page

### PR DESCRIPTION
**Pull request by DanaOrr**
Signed-off-by: Dana Orr <dorr@redhat.com>

## 📝 Description
Installing the latest version of react-charts made the number inside the donuts visible in virtual machines per template card on overview page.

## 🎥 Demo
Before:
image

After:
image

### CODE REVIEW

**Comment by yaacov** [comment]
@DanaOrr it looks like the new version breaks things ?
can you look at the unit test fails ? maybe they are easy to fix ?

**Comment by yaacov** [comment]
cc:// @pcbailey

**Comment by hstastna** [comment]
I've tested this PR and it fixes the bug. Looks good to me 👍🏽

**Pull request merged**
