### PR TITLE
Add quick starts section

### PR DESCRIPTION
**Pull request by pcbailey**
This PR adds the quick starts section and the hide/show kebab action to the getting started card of the virtualization overview page.

The content of the quick starts section will be updated in a separate PR.

### Screenshots:

Getting started card showing:
Selection_103

Getting started card hidden and show button displayed in header:
Selection_101

### CODE REVIEW

**Comment by yaacov** [comment]
needs 'yarn i18n'

**Comment by glekner** [comment]
please rebase and run `yarn && yarn i18n` for updated parser.

**Pull request merged**
