### PR TITLE
CNV-43951: Upgrade Node version

### PR DESCRIPTION
**Pull request by upalatucci**
## 📝 Description

upgrade eslint-plugin-jsdoc to support node >= 18
Enforce node >= 18.x

### CODE REVIEW

**Comment by metalice** [comment]
i think the workflow and images should be updated to include node 18

**Comment by upalatucci** [comment]
@metalice fixed

**Comment by metalice** [comment]
/retest
@upalatucci if its not passing please try to fix

**Comment by metalice** [comment]
@upalatucci 
please replace those 3 lines in package.json and see if its passing

`    
"test-cypress": "cd cypress && npx cypress open --config-file ./cypress.json --env openshift=true",
 "test-cypress-docker": "echo 'visit http://localhost:10000' && cd cypress && DISPLAY=:14 LIBGL_ALWAYS_INDIRECT=0  npx cypress open --config-file ./cypress.json --env openshift=true",
"test-cypress-headless": "cd cypress && npx --max-old-space-size=4096 cypress run --config-file ./cypress.json --env openshift=true --headless",`

**Pull request merged**
