### PR TITLE
Bug 2091856: Edit Boot Source Ref

### PR DESCRIPTION
**Pull request by upalatucci**
## 📝 Description

Two different description labels when 'Edit boot source reference' disabled

- `Template does not use boot source reference` when a template does not have a sourceRef datavolume
- `Boot source reference cannot be edited` when the template's data source is part of DataImportCron.

## 🎥 Demo

Screenshot from 2022-06-09 10-37-56
Screenshot from 2022-06-09 10-37-43
Screenshot from 2022-06-09 10-37-35

### CODE REVIEW

**Comment by yfrimanm** [comment]
LGTM

**Comment by apinnick** [comment]
@yfrimanm @yaacov @upalatucci 

The capitalization is inconsistent. "Template" is capitalized in the menu items. Patternfly uses sentence case, so the menu items should be "Edit template", "Clone template", and "Delete template".

**Comment by upalatucci** [comment]
Thanks @apinnick, we'll fix that

**Comment by upalatucci** [comment]
[here](https://github.com/kubevirt-ui/kubevirt-plugin/pull/596)

**Pull request merged**
