### PR TITLE
CNV-37814: Upgrade to PFv5

### PR DESCRIPTION
**Pull request by avivtur**
## 📝 Description

Upgrading Patternfly to version 5.1.1
Upgrading SDK packages to 1.0.0 as they support PFv5

### CODE REVIEW

**Comment by metalice** [comment]
managed to reproduce. trying to make a solution

**Comment by metalice** [comment]
ok, I managed to figure it out; now it's working for me locally, but my laptop has 64 GB ram; I don't know the ci ram, lets hope its more then 8
let's try
image

u can remove this added line form package.json scripts.build

**Comment by avivtur** [comment]
/hold
cypress failing due to a warning coming from SDK packages.

**Pull request merged**
