### PR TITLE
[release-4.15] CNV-38295: Move SSH using virtctl helper text to info popover

### PR DESCRIPTION
**Pull request by pcbailey**
## 📝 Description

This PR adds the example command to the info icon popover and beneath the "SSH secret not configured" text. It removes the example command when the SSH secret is configured.

Jira: https://issues.redhat.com/browse/CNV-38295

### Before - configured
ssh-access-helper-text-BEFORE-2024-01-24_09-11

### Before - not configured
ssh-using-virtctl-not-configured-popover-BEFORE-2024-01-29_22-03

### After - configured
ssh-using-virtctl-configured-popover-AFTER-2024-01-29_21-24

### After - not configured
ssh-using-virtctl-not-configured-AFTER-2024-01-29_21-36

### CODE REVIEW

**Comment by hstastna** [comment]
Hi @pcbailey, could you, please, add "before" and "after" screenshots to the PR? Looks like this is making some visual changes in our UI :) Thanks!

**Review by hstastna — COMMENTED** [review]
Looks good to me! Just a little thing: IMO using "<path_to_sshkey>" in the example command makes the example being not quite an example. I'd expect something else there, some example path instead, same as it used to be before (see the pictures in the related Jira ticket). I'd suggest not to use the totally same string for both the command and for the example command. Doing this makes the existence of the example useless in case of SSH being already configured. I'd suggest to change this also in the main branch.

**Comment by pcbailey** [comment]
@hstastna This is a manual backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1747. The design was already approved by Yifat and merged into main. I'll add the screenshots from the original PR.

**Pull request merged**
