### PR TITLE
CNV-37414: Fix jumping bug and make user provided instancetype working

### PR DESCRIPTION
**Pull request by metalice**
## 📝 Description

Making the user instancetype working
user-instacetype

### CODE REVIEW

**Review by hstastna — COMMENTED** [review]
Hi @metalice, the code looks good to me! Could you, please, just add some picture/video about how it looks before vs. after to make this PR more clear and to make us sure we are achieving what's expected? Thanks!

**Comment by metalice** [comment]
> Hi @metalice, the code looks good to me! Could you, please, just add some picture/video about how it looks before vs. after to make this PR more clear and to make us sure we are achieving what's expected? Thanks!

For before u can test main now. It simply not working at all when selecting user provided

**Comment by hstastna** [comment]
> > Hi @metalice, the code looks good to me! Could you, please, just add some picture/video about how it looks before vs. after to make this PR more clear and to make us sure we are achieving what's expected? Thanks!
> 
> For before u can test main now. It simply not working at all when selecting user provided

Yes, of course, thanks! Just I don't see any difference between this and the main branch. This is why I asked for more info about before vs. after.

**Comment by metalice** [comment]
> > > Hi @metalice, the code looks good to me! Could you, please, just add some picture/video about how it looks before vs. after to make this PR more clear and to make us sure we are achieving what's expected? Thanks!
> > 
> > 
> > For before u can test main now. It simply not working at all when selecting user provided
> 
> Yes, of course, thanks! Just I don't see any difference between this and the main branch. This is why I asked for more info about before vs. after.

when u try to create a VM from user provided instance type its working for u on main?

**Pull request merged**
