### PR TITLE
Add activity card to cluster overview

### PR DESCRIPTION
**Pull request by pcbailey**
This PR adds the activity card to the overview page.

Screenshot:
Selection_074

### CODE REVIEW

**Comment by yaacov** [comment]
/retitle [WIP] Add activity card to cluster overview

**Comment by florkbr** [comment]
@pcbailey looks like there are some linter errors so the build didn't run in PROW on this PR, however I believe we have a fix for the build errors you were seeing locally: https://github.com/openshift/console/pull/11381. We will work on getting that published ASAP.

**Pull request merged**
