### PR TITLE
Approximated disk quantity in list

### PR DESCRIPTION
**Pull request by upalatucci**
## 🎥 Demo
Before
Screenshot from 2022-04-05 10-24-34

After
Screenshot from 2022-04-05 12-09-32

### CODE REVIEW

**Comment by avivtur** [comment]
why is the size rounded to 33Gi instead of ~33.59Gi like it would have shown on the disks list after VM creation?

**Comment by upalatucci** [comment]
right I'll add a precision parameter to the function

**Review by avivtur — APPROVED** [review]
looks good nice work :)

**Pull request merged**
