### PR TITLE
[release-4.12] Bug 2172832: CNV-23494 Ssh select load balancer

### PR DESCRIPTION
**Pull request by upalatucci**
## 📝 Description

manual cherry-pick of three prs 
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1036
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1043
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1052

Ticket with its two bugs

### CODE REVIEW

**Comment by hstastna** [comment]
> Ticket with its two bugs

@upalatucci which 2 bugs are related to this PR? Or can you, please, provide the links of all the related tickets/bugs explicitly in the description of the PR? As there is no any clear number in the title. Thanks in advance! :)

**Comment by upalatucci** [comment]
#1036 is the feature
#1043 is a second pr that fixes a bug but I've considered it as part of the feature
#1052 is the bug https://bugzilla.redhat.com/show_bug.cgi?id=2168032

**Comment by hstastna** [comment]
@upalatucci Note that we need a BZ ticket to 4.12, if we want to backport a fix done in 4.13 to 4.12.

**Comment by upalatucci** [comment]
Okay. The bug was created by the actual feature that I implemented. So backporting the feature means backporting also the bug. I  didn't think about that. But if we need to do that, I'll do it

**Comment by upalatucci** [comment]
the bugzilla ticket for the bug backport is this: https://bugzilla.redhat.com/show_bug.cgi?id=2172832

**Pull request merged**
