### PR TITLE
Bug 2136051: Fix Name jumping and fill generatable parameters

### PR DESCRIPTION
**Pull request by upalatucci**
## 📝 Description

DrawerCreateForm now generates only one time the vmName

Now in the customizeform, the code will process template generatable parameters like name, cloud-init passwords 
and so on.

Filling the corresponding inputs with the value generated by the backend.

Note: deleted test as `CustomizeVirtualMachine` was like a cypress test using jest. A lot of mocked resources and functions ... 
Just a waste of time trying to get it working after a small modification. (I made those tests so i can talk like that) 

## 🎥 Demo

[Screencast from 19-10-2022 14:57:25.webm](https://user-images.githubusercontent.com/29160323/196697233-04bd9795-23ec-4664-8bbe-79633cdd9a42.webm)

### CODE REVIEW

**Comment by upalatucci** [comment]
Thanks guys for the reviews! 
I just fixed the pr following the suggestions :-)

**Comment by upalatucci** [comment]
Removed also tests.
They were too much of an obstacle for development instead of being useful. Too much mocks. Something easy to do with cypress

**Comment by avivtur** [comment]
looks good to me,
let's wait for @metalice to also do a final look

**Pull request merged**
