### PR TITLE
Bug 2103806: PVC 404

### PR DESCRIPTION
**Pull request by upalatucci**

### CODE REVIEW

**Review by hstastna — APPROVED** [review]

**Review by avivtur — COMMENTED** [review]
Hi Ugo thanks for this PR :) 
The usage of `kind` prop should be depracated, please use instead like so
 `groupVersionKind={modelToGroupVersionKind(PersistentVolumeClaimModel)}` instead of `kind={PersistentVolumeClaimModel.kind}` in all relevant places

**Comment by upalatucci** [comment]
Thanks @avivtur nice catch!

**Comment by avivtur** [comment]
/lgtm
:100: :100:

**Pull request merged**
