### PR TITLE
[e2] add test to create vm from url

### PR DESCRIPTION
**Pull request by gouyang**
## 📝 Description

> Add a brief description

## 🎥 Demo

> Please add a video or an image of the behavior/changes

### CODE REVIEW

**Comment by gouyang** [comment]
@yaacov It looks the VM created from URL is not schedulable in prow.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kubevirt-ui_kubevirt-plugin/329/pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws/1519181661151956992/artifacts/kubevirt-e2e-aws/tests/artifacts/gui-test-screenshots/screenshots/catalog/create-vm-from-catalog.spec.ts/1_Create%20VM%20from%20catalog%20--%20ID(CNV-)%20Create%20VM%20from%20URL%20source%20(failed).png

**Comment by yaacov** [comment]
/retitle [e2] add test to create vm from url

**Comment by yaacov** [comment]
@gouyang can we close this T1 (on prow) test in favor of a T2 test on QE infra?
Prow tests that relay on network connection may be flaky

**Pull request closed without merging**
